import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {
  AiFillTwitterCircle, 
  AiFillLinkedin, 
  AiFillYoutube} from 'react-icons/ai'

export default function Home() {
  return (
    // git test
    <>
      <Head>
        <title>Franco Krepel Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="bg-white px-10">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons"> Franco Krepel </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl"/>
                </li>
              <li className="bg-gradient-to-r from-cyan-400 to-teal-400 text-white px-3 py-1 rounded-md ml-8"><a href='#'>Resume</a></li> 
            </ul>
          </nav>

          <div className="text-center p-10">
            <h2 className="py-2 text-5xl font-medium text-teal-400">
               Franco Krepel
            </h2>
            <h3 className="text-2xl py-2"> 
            hello hello butt face
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              I am da franco and i am a cs major n like an econ minor
              n stuff but i need to work on dis so i can do good on my project
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
        </section>
      </main>
    </>
  )
}
